### ISSUE TITLE
Falta de comentarios en el Test

### ISSUE THREAD

**Issue by javierponferradalopez** [gboquizo/Practica_Issue_Guillermo#1]
Realiza los cambios, para que @jaimerabasco te evalúe.
https://github.com/gboquizo/Practica_Issue_Guillermo/blob/master/src/guillermoBoquizoSanchezAcumulaSumas/Test.java#L14-L16
https://github.com/gboquizo/Practica_Issue_Guillermo/blob/master/src/guillermoBoquizoSanchezAcumulaSumas/Test.java#L66-L67
https://github.com/gboquizo/Practica_Issue_Guillermo/blob/master/src/guillermoBoquizoSanchezAcumulaSumas/Test.java#L84-L85

**Comment by gboquizo** [comment]
De acuerdo @jponferrada26 , vamos a corregir esas carencias para que @jaimerabasco las evalúe

#1

**Comment by javierponferradalopez** [comment]
Ok ;)
